# Generated by Django 3.2.1 on 2021-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_inference', '0002_auto_20210812_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='ct_srv_dst',
            field=models.FloatField(default=100),
        ),
    ]
