# Generated by Django 3.2.1 on 2021-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_inference', '0003_inference_ct_srv_dst'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='task_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
