# Generated by Django 3.2.1 on 2021-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(default='', max_length=100)),
                ('state', models.TextField(default='', max_length=100)),
                ('proto', models.TextField(default='', max_length=100)),
                ('attack_cat', models.TextField(default='', max_length=100)),
                ('ID_NO', models.FloatField(default=100)),
                ('dur', models.FloatField(default=100)),
                ('spkts', models.FloatField(default=100)),
                ('dpkts', models.FloatField(default=100)),
                ('sbytes', models.FloatField(default=100)),
                ('dbytes', models.FloatField(default=100)),
                ('rate', models.FloatField(default=100)),
                ('sttl', models.FloatField(default=100)),
                ('dttl', models.FloatField(default=100)),
                ('sload', models.FloatField(default=100)),
                ('dload', models.FloatField(default=100)),
                ('sloss', models.FloatField(default=100)),
                ('dloss', models.FloatField(default=100)),
                ('sinpkt', models.FloatField(default=100)),
                ('dinpkt', models.FloatField(default=100)),
                ('sjit', models.FloatField(default=100)),
                ('djit', models.FloatField(default=100)),
                ('swin', models.FloatField(default=100)),
                ('stcpb', models.FloatField(default=100)),
                ('dtcpb', models.FloatField(default=100)),
                ('dwin', models.FloatField(default=100)),
                ('tcprtt', models.FloatField(default=100)),
                ('synack', models.FloatField(default=100)),
                ('ackdat', models.FloatField(default=100)),
                ('smean', models.FloatField(default=100)),
                ('dmean', models.FloatField(default=100)),
                ('trans_depth', models.FloatField(default=100)),
                ('response_body_len', models.FloatField(default=100)),
                ('ct_srv_src', models.FloatField(default=100)),
                ('ct_state_ttl', models.FloatField(default=100)),
                ('ct_dst_ltm', models.FloatField(default=100)),
                ('ct_src_dport_ltm', models.FloatField(default=100)),
                ('ct_dst_sport_ltm', models.FloatField(default=100)),
                ('ct_dst_src_ltm', models.FloatField(default=100)),
                ('is_ftp_login', models.FloatField(default=100)),
                ('ct_ftp_cmd', models.FloatField(default=100)),
                ('ct_flw_http_mthd', models.FloatField(default=100)),
                ('ct_src_ltm', models.FloatField(default=100)),
                ('ct_srv_dst', models.FloatField(default=100)),
                ('is_sm_ips_ports', models.FloatField(default=100)),
            ],
        ),
    ]
