# Generated by Django 3.2.1 on 2021-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_updated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predict',
            name='task_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
