# Generated by Django 3.2.1 on 2021-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_updated', '0002_auto_20210812_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='probability',
            field=models.FloatField(default=None),
        ),
    ]
